### ISSUE TITLE
As a User I want to view my Invoices so that I can keep track of my payment and receipts.

### ISSUE THREAD

**Issue by Dessezar** [KYH-Net23/CustomerInvoices#2]
# [Demi and Cristoffer]

## *Acceptance Criterias* 
- [ ] The user should be able to view a visible list of all invoices
- [ ] Each invoice should display the invoice date, total amount and payment status
- [ ] (User should be able to sort and filter the invoices)
- [ ] (User should receive an email notification when a new invoice is created)

## *Tasks*
- [ ] Create invoiceDataModel (if it doesn't exist)
- [ ] Create invoiceViewModel (if it doesn't exist)
- [ ] Make a button to view invoices.
- [ ] Get invoice information from database
- [ ] Implement a method to search and filter.
- [ ] Create the frontend to display a list of invoices (with general information) 
- [ ] Make a show more option to see all information on the invoice (or redirect?)
- [ ] Implement email funktion to send a reminder when the invoice is past the due date.
- [ ] Create a back button.  

## *Testcases*

- [ ] ***Testcase 1: View and/or payment of invoice*** 

* Prerequisites: you are logged in as a user
* Steps:
        1. navigate to my profile
        2. navigate to Invoices
        3. chose the invoice you want to see (either by scrolling the list, filtering or searching for a specific invoice)
        4. chose to view invoice

* Expected result: 
user can see a complete invoice with all information (amount, products and more)
